### ISSUE TITLE
The 6 most popular products list on the front page should contain unique items

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#120]
**Describe the bug**
The list of popular products contains duplicate products.

**To Reproduce**
1. Go to the frontpage on localhost
2. Open devtools
3. Notice the multiple key warning in the console
4. See duplicate products

**Expected behavior**
The top 6 popular products should be unique

**Screenshots**
![Skjermbilde 2022-08-08 kl  08 13 29](https://user-images.githubusercontent.com/1568252/183351541-e6de46a5-d39b-41dc-8e49-afbee2221bdc.png)

**Comment by ShikhaMishra9** [comment]
Merged
