### ISSUE TITLE
Investiagate possibility of extracting data from Collibra and put it into Algolia

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#128]
## Todo
- Need to figure out if it's OK to store these kind of data in a 3. party service like Algolia
- Which data should we store and it is possible

**Comment by nilsml** [comment]
Asset endpoint gives us number of search results.

**Comment by nilsml** [comment]
Still left to do is to check with someone if we actually can store this data outside of Equinor

**Comment by aronhoyer** [comment]
to add to what @nilsml said:
yes, the `/assets` endpoint gives us the number of total assets matching the parameters given. additionally it's a paginated endpoint, so we can recursively call the endpoint until we've gone through all the approved data product assets.
