### ISSUE TITLE
Implement Cancel button for checkout wizard

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#130]
## Acceptance criteria
- When the user clicks on the `cancel` button in the checkout flow, he/she will be redirected back to the corresponding asset detail view

## Testing
- Click on an asset to get to the detail view
- Click on the `request access` button
- You should be taken to the checkout flow
- Click `cancel`
- You should be redirected to the asset detail view

**Comment by aronhoyer** [comment]
Where should the user be navigated to if they cancel?

**Comment by aronhoyer** [comment]
With the decision to move to single checkout (see #151) we know with a 100% certainty where the user started the checkout from (i.e. an asset detail view). This means we can simply redirect them back to the given asset detail view
