### ISSUE TITLE
Make the content in the shopping cart more robust

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#133]
As a user I want to persist my content in the shopping cart if I refresh the browser window

## Technical background
For the time being, the content in the shopping cart is only saved to the redux store, so it's just client side.

## Acceptance criteria
1. The content in the shopping cart is still available when the browser window is refreshed

## In order to test this User Story, do
1. Add an item to the shopping cart
2. Refresh the browser window
3. Verify that the content is still available by
- The number of items on the shopping cart icon
- By navigating to `/cart`

**Comment by nilsml** [comment]
As long as we don't have a shopping cart, this is not needed. Close or what? @wenche

**Comment by wenche** [comment]
Yup @nilsml
