### ISSUE TITLE
Follow EDS guidelines - revisit components

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#134]
Also have a look at accessibility and responsiveness

(at least) Look at 
- Cards
- Tabs
- Chips/tags
- Add a button for the search field

**Comment by wenche** [comment]
The EDS search component does not have a button in the examples. Also suggesting to not  spend more time on the search input if we are switching search engine as the EDS search doesn't work well with livesearch

**Comment by wenche** [comment]
I have created several new issues so we are able to prioritise accordingly

- #135 
- #138 
- #140 
- #143 
- #144 
- #145 
- #147

**Comment by wenche** [comment]
Can we close this? De som tier, samtykker

**Comment by nilsml** [comment]
Did you have a look at this one @aronhoyer? Need to close as much as possible before sprint demo.

**Comment by aronhoyer** [comment]
@nilsml no, haven't done any ui work this sprint

**Comment by aronhoyer** [comment]
@nilsml no, haven't done any ui work this sprint
