### ISSUE TITLE
Use EDS Top bar component as the header

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#135]
In order to standardize the user interface to Equinor applications, we should use the EDS top bar instead of our custom header

TODO: Figure out if it's OK to add the shopping cart icon to the actions container. What about the browse icon?

Edit: It _does_ actually use the EDS topbar, didn't realise that 😅  But it doesn't quite look like that design wise, probably because of the additional cart and account icon on the top and the placement of the content?

## Acceptance
1. Figma sketches are updated to correctly lay out an EDS compliant header
2. The header uses the Top bar component

**Comment by wenche** [comment]
Potentially relates to #150 as the EDS Top bar is not responsive

**Comment by aronhoyer** [comment]
closed by #164
