### ISSUE TITLE
Update communities filter to utilise EDS

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#138]
In order to utilise EDS we should update the communities filter tags to use EDS.

## Note
- The EDS chip might not be the best fit here as it does not have a toggle function
- The documentation says 
> Chips should make tasks easier to complete, or content easier to sort.

but it's a litte bit hard to see how exactly they can be used for this
- If we are planning to use Algolia, it might eventually be a better fit to use a list of EDS checkboxes as Envis does 

## Acceptance criteria
1. Update Figma sketches
3. Use EDS in the communities filter

**Comment by ShikhaMishra9** [comment]
Using Checkbox here as that looked better fit.  Also looks good in  figma sketches  as well.
