### ISSUE TITLE
Improve accessibility for the responsibility tab

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#143]
In order to make the asset detail's responsibility tab easier to understand we should use better semantic.

## Suggestions
- Preferred: Since this is actual tabular data, we should use the EDS table
- _Or_ use a header element for the sub titles and an unordered list for the name + phone numbers

## Acceptance
tbd according to the chosen solution Figma + code

**Comment by ShikhaMishra9** [comment]
Using EDS Table here for displaying data in list.
