### ISSUE TITLE
See if it makes sense to use the EDS progress indicators instead of the FullPageSpinner

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#145]
In order to utilise EDS we should look into if it makes sense to avoid the selfmade FullPageSpinner component.

I guess this is done by a reason, so it might not be a good idea 🤔

## Acceptance criteria

1. `FullPageSpinner` no longer exists and is not referred to in code :+1:

**Comment by aronhoyer** [comment]
The `FullPageSpinner` component was implemented before I learned that the `Progress` component even existed 😅 so we should definitely retire `FullPageSpinner`.

**Comment by ShikhaMishra9** [comment]
#169
