### ISSUE TITLE
Add login

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#15]
The Collibra API has an endpoint that lets us authenticate the user. Authentication is session based, and the endpoint will return a session ID, in addition to some user data.

**Comment by aronhoyer** [comment]
we might need to implement SSO in order to get authentication working. not really sure how we would go about that. could either of you advice on that @ovineq @nilsml ?

**Comment by ovineq** [comment]
Let's ask how to go about it in today's meeting, or at least find out who we can talk to about it. 
Since we're interfacing with the Collibra team, I reckon we'll have to conform their authorization flow.
