### ISSUE TITLE
Utilize i18n package for static text

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#16]
To make static texts easier to maintain, and potential translations down the line easier to implement, we should add a package like [next-i18next](https://www.npmjs.com/package/next-i18next).

This will allow us to store static text in one place, which will make it easier to maintain copy.

### Acceptance criteria
- All texts are added to a file for English text
- The components use these texts instead of hard coded text inside the code itself

**Comment by aronhoyer** [comment]
Where do you land on this @nilsml and @ovineq? Should we implement this from the get-go, or wait until there's a need for translations, if ever?

**Comment by ovineq** [comment]
I think we could await this, unless PO has stated that it's a hard requirement.

**Comment by nilsml** [comment]
Agree with @ovineq. We don't know if it will ever be a requirement yet.
