### ISSUE TITLE
Investigate which workflow to use for checkout

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#161]
**In order to initiate the correct workflow, we need to figure out which workflow to trigger**

In Collibra, there are a bunch of predefined workflows that each trigger different things for different people.

So in order to initiate the correct workflow for checkout, we need know the correct workflow to initiate.

There's also a question of whether we should persist the workflow ID somewhere or if we should find it each time a user wants to check out.

**Comment by nilsml** [comment]
Create User Story for actually implementing this feature

**Comment by aronhoyer** [comment]
we should be able to easily find the workflow definition for the request access workflow by sending a `GET` request to collibra's `/workflowDefinitions` endpoint with the `assetId` as a query parameter:

```js
HttpClient.get(`${config.COLLIBRA_BASE_URL}/workflowDefinitions`, {
  query: { assetId: "abc123" },
})
```
