### ISSUE TITLE
Parse and sanitize HTML from Collibra

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#192]
**As a Developer I want to not render HTML in the app, so that we can control layout**

Collibra descriptions and other rich text fields are stored as HTML and provided through the API as an HTML string. This creates issues on our end when we want to index Algolia for search and want to render the asset view.

## Acceptance criteria
1. Rich text fields are converted to a portable format that is renderable by a client
2. The portable data is usable by Algolia

## In order to test this User Story, do
TBD

**Comment by nilsml** [comment]
Replaced by AB#78388
