### ISSUE TITLE
Create adapter service

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#193]
**As an Equinor employee, I want Data Marketplace to not be tightly coupled to a data source, so that I can easily replace the data source if necessary**

## Acceptance criteria
1. It's possible to add/replace/remove a data source without the app falling over

## In order to test this User Story, do
1. Add/replace/remove a data source (i.e. Collibra)

**Comment by nilsml** [comment]
Replaced by AB#78389
