### ISSUE TITLE
Create Algolia search indexer service

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#194]
**As a User, I want to search for up-to-date data products, so that I can find up-to-date results**

Create a service that runs continuously to keep the Algolia index up to date.

## Acceptance criteria
1. Decision has been made as to how often the service should run
2. Requests data through the adapter service (depends on #193 and #192)
3. Algolia contains searchable data

## In order to test this User Story, do
TBD

**Comment by nilsml** [comment]
Replaced by AB#38393
