### ISSUE TITLE
Access IT API integration

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#196]
**As a User, I want to the request access application to be seamless, so that only need to fill out one request form**

Users currently need to duplicate their request access application in both Collibra (through Data Marketplace) and Access IT. Integrating with the Access IT API might make it possible to streamline the process so users only need to fill out the application in Data Marketplace.

## Acceptance criteria
1. Application gets sent to Collibra, and workflow is consequently instantiated.
2. Application gets sent to Access IT, and task consequently gets sent to the correct person.
3. Optional: Request automatically gets approved if they are registered as an employee of the community/department of the department that owns the data product.

## In order to test this User Story, do
1. Request access to a data product.

**Comment by nilsml** [comment]
Replaced by AB#78396
