### ISSUE TITLE
Implement checkout process

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#28]
- [x] #101 
- [x] #151
- [x] #130 
- [x] #176
- [x] #177 
- [x] #190 

[AB#78587](https://dev.azure.com/EquinorASA/d02c350d-092d-41bf-a812-f05d5d8ad1b0/_workitems/edit/78587)

**Comment by nilsml** [comment]
I guess this should be a user story with several sub-tasks..?

**Comment by wenche** [comment]
Do we do this at all since we already have several other tasks covering each separate step?
