### ISSUE TITLE
Discuss initial high level architecture and document it in the C4 format

### ISSUE THREAD

**Issue by nilsml** [equinor/data-marketplace#5]

**Comment by aronhoyer** [comment]
Since the scope has changed a bit, we can visit this once the new developers join the team.

**Comment by nilsml** [comment]
This is something we should start looking at quite soon

**Comment by nilsml** [comment]
First version of diagrams done. Waiting for merge of AC PR for including the diagrams in the contract.

**Comment by aronhoyer** [comment]
Closed by equinor/architecturecontract#913
