### ISSUE TITLE
Evaluate React form libraries for use in checkout

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#61]

**Comment by aronhoyer** [comment]
I'm going to start with [React Hook Form](https://react-hook-form.com). If anyone has other suggestions please sound off!

**Comment by wenche** [comment]
React hook form is my preferred as well!

**Comment by aronhoyer** [comment]
I've been looking around for other libraries, but i think we'll just go for react hook form. it's the simplest and most expandable library i've been able to find as of now.
