### ISSUE TITLE
Checkout: Restore checkout state on refresh

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#83]
When a user refreshes during the checkout process or navigate back and/or forward in the checkout process, they should automatically get redirected to the step they were on and state should be restored

**Comment by wenche** [comment]
Doesn't this already work since each step is a separate page using Router

**Comment by aronhoyer** [comment]
Yes, but no. The state isn't correctly restored.

**Comment by wenche** [comment]
It doesn't work properly for the wizard navigation steps
