### ISSUE TITLE
Search: Make it easier to understand that the use of filters gave no hits

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#85]
The text for no hits in the search is a little bit misleading when it's actually the use of filters that resulted in a no hit. Look into to improve the user experience here.

![Image](https://user-images.githubusercontent.com/1568252/180970436-510de095-6389-4577-8115-277d1c872a81.png)

vs the actual result for `test`

![Image](https://user-images.githubusercontent.com/1568252/180970659-717b35c6-04dd-4288-9c86-590b6ef68893.png)

**Comment by aronhoyer** [comment]
We should inform the user in some way that the combination of the search term **and** the selected filters, resulted in no results, not just that the search term returned no results.
